server:
  port: 8081
spring:
  application:
    name: "Request"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5435
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    co.com.pragma: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600